# Core Infrastructure Variables

# Docker Configuration
docker_swarm_enabled: false

# Fail2Ban Configuration
fail2ban_enabled: true

# Traefik Configuration
traefik_enabled: true
traefik_email: "{{ infra_email }}"
traefik_acme_bucket: "traefik-acme-bucket"
